name: Run Pytest
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest -v
